### PR TITLE
bn.xml

### PR DESCRIPTION
**Pull request by dutchman1990**
TWRP translation file in Bengali language. check here for more details https://en.wikipedia.org/wiki/Bengali_language

### CODE REVIEW

**Comment by Dees-Troy** [comment]
Line 4 needs to be changed to Bengali

**Comment by dutchman1990** [comment]
done. please check now.

**Comment by dutchman1990** [comment]
You'll notice that in line 24 to 31 I didn't make any changes or make partial changes, because these are some words that are directly adopted from English and there are no suitable or prefect translation available.

**Comment by bigbiff** [comment]
Any patches need to be submitted to android_bootable_recovery at https://gerrit.omnirom.org for inclusion.

**Pull request closed without merging**
