### PR TITLE
Italian translation update

### PR DESCRIPTION
**Pull request by bovirus**
Italian translation update

### CODE REVIEW

**Comment by CaptainThrowback** [comment]
Submit through Omnirom gerrit, not as a pull request here.

**Comment by bovirus** [comment]
Hoiw can contact Omnirom Gerrit?
I already completed OmniROM translation (OmniROM Italian translation is 100% translated).
Please contact Gerrit and he can confirm it.

**Comment by CaptainThrowback** [comment]
If you've already submitted to Gerrit, there's no need to submit anything else. However if you want your translation to be viewed or merged, you should add Dees_Troy as a reviewer. I do see this: https://gerrit.omnirom.org/#/c/16899/ on Gerrit.

**Comment by bovirus** [comment]
The translation https://gerrit.omnirom.org/#/c/16899/ it's a partial translation that "seems" copied by an Italian translation made by other guys (freedgt) on Androidiani (Italian forum about Android).
The translation on https://gerrit.omnirom.org/#/c/16899/ contains some errors (Fornitore is not right translation - It's produttore / contains many strings with uppercase on any word - In Italian just first is in uppercase) and contains many strings untranslated,.
For me that I'm working in my spare time as profesisonal translation for freeware projects I believe that could be more bettere.
I uploaded on geerit.omnirom my proposal for translation (100% translated) and I made a pull request (https://github.com/omnirom/android_bootable_recovery/pull/62)
How can I add Dees_Troy as reviewer?
Thanks.

**Comment by bovirus** [comment]
@Dees-Troy
Someone could please update the Italian language that I uploaded?
I just also revsied it but I'd like to know is someone upload 1st version.
Thanks.

**Comment by bovirus** [comment]
@CaptainThrowback 
I posted my language proposal many many days ago but no answer (accept/dismiss it).
Which is the sense that someone add a new language and no one of the author answer?
I checked that also other author proosed italian.
And others proposed other new languages.
But no one answer. It's completly a non sense.
Thanks.

**Comment by CaptainThrowback** [comment]
Even if those patches were merged now, it won't make any difference until there's another TWRP release. @Dees-Troy will likely review and merge them all before the next release. Please be patient.

**Comment by bovirus** [comment]
@CaptainThrowback 
I believe that the new language should be included as it will be available.
Many user developped a new language (hu/zh_ch/zh_tw/etc) that are not included in current build and they developped the langauge tos ee it from now..
Then if someone download the zip file for develop a new TWRP it included always the latest language available.
The languages are different things issues than code fix.
I posted a request to @TeamWin-Gerrit. No answer.
I posted a request to @Dees-Troy (here and on xda). No answer.
This TWRP It seems a project leave alone.

**Comment by CaptainThrowback** [comment]
For people producing their own builds, those patches can be cherry-picked from Gerrit for inclusion.

**Comment by bovirus** [comment]
@CaptainThrowback 
The situation about languages from Gerrit repository seems the same.
Most of the user download the ZIP file from repository (not use github sync).

**Comment by bigbiff** [comment]
Any patches need to be submitted to android_bootable_recovery at https://gerrit.omnirom.org for inclusion.

**Pull request closed without merging**
