### PR TITLE
some fixes for your consideration

### PR DESCRIPTION
**Pull request by sebastian404**
These are some fixes I made when porting the recovery to some Huawei devices, hopefully you find them useful.

### CODE REVIEW

**Comment by ViViDboarder** [comment]
Most of this looks good, but look at the comments on [fix RGB_565 pixel format](https://github.com/sebastian404/Team-Win-Recovery-Project/commit/87436a8baae73d7d2f32e5cb31c88d656591b479)

**Comment by sebastian404** [comment]
A few more fixes I've found as I port to more devices

I only have have RGB_565 devices so I'm unable to test the upside-down display with that

**Comment by Dees-Troy** [comment]
If you remove the events changes from the pull request, I'll be happy to merge the other changes.  You can submit the events changes for single touch separate and I can try to troubleshoot from there.  Sometime hopefully in the next few days we'll be able to get a gerrit instance up and and running and we'll have people submit code through that for review and merging.  Thanks.

**Comment by LalitMaganti** [comment]
Upside down display works.

**Comment by Dees-Troy** [comment]
I see that you found our gerrit instance.  I kind of made a mess of things today by merging cm9wip into master.  I also updated the guide on rootzwiki to reflect some of those changes.  All of the changes that you submitted to gerrit are now accepted and hopefully I didn't botch the process too badly.  I'm going to close this pull request.  Thanks for submitting your changes.  It's greatly appreciated!

**Pull request closed without merging**
