### PR TITLE
add support multi language fonts

### PR DESCRIPTION
**Pull request by syhost**
support multi langage fonts,
for example chinese.

### CODE REVIEW

**Comment by imrasalghul** [comment]
Can one of the admins verify this patch?

**Comment by Dees-Troy** [comment]
If you have code changes to submit those should be pushed to our gerrit instance. A guide can be found here:
http://teamw.in/twrp2-gerrit

Instead of creating a graphics_cn.c file and putting your changes in a separate file the changes should beiincluded in the regular graphics.c so that we can see what is actually changed. I also only want the changes needed for the language support. The changes to adb sideload should be a separate submission. 

Sorry for getting back so late on this but I have been very busy with a new baby. Thanks for your interest in TWRP.

**Comment by xuefer** [comment]
http://teamw.in/twrp2-gerrit File Not Found

opening review.teamw.in

The server at review.teamw.in can't be found, because the DNS lookup failed. DNS is the network service that translates a website's name to its Internet address. This error is most often caused by having no connection to the Internet or a misconfigured network. It can also be caused by an unresponsive DNS server or a firewall preventing Google Chrome from accessing the network.

**Comment by bigbiff** [comment]
Any patches need to be submitted to android_bootable_recovery at https://gerrit.omnirom.org for inclusion.

**Pull request closed without merging**
